//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReport
    {
        public decimal ReportID { get; set; }
        public string ReportType { get; set; }
        public string Hospital { get; set; }
        public string Doctor { get; set; }
        public string Date { get; set; }
        public string FileURL { get; set; }
        public decimal UserID { get; set; }
    
        public virtual UserCredential UserCredential { get; set; }
    }
}
