//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDoctor
    {
        public decimal DoctorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string RelatedHostpital { get; set; }
        public string Specialty { get; set; }
        public string Address { get; set; }
        public decimal ContactNumber1 { get; set; }
        public decimal ContactNumber2 { get; set; }
        public string PrimaryDoctorMark { get; set; }
        public decimal UserID { get; set; }
    
        public virtual UserCredential UserCredential { get; set; }
    }
}
