//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHospital
    {
        public decimal HospitalID { get; set; }
        public string HospitalName { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
        public decimal ContactNumber1 { get; set; }
        public decimal ContactNumber2 { get; set; }
        public string PrimaryMark { get; set; }
        public decimal UserID { get; set; }
    
        public virtual UserCredential UserCredential { get; set; }
    }
}
